In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import scipy.io as sio

In [6]:
#1. Crear una matriz de Numpy aleatoria de 4 dimensiones y un size de 1200000 
dim1 = 40
dim2 = 10
dim3 = 30
dim4 = 100
size = dim1 * dim2 * dim3 * dim4
matriz4d = np.random.rand(dim1, dim2, dim3, dim4)
print(f"La forma de la matriz 4D es: {matriz4d.shape}")
print(f"El tamaño de la matriz 4D es: {matriz4d.size}")


La forma de la matriz 4D es: (40, 10, 30, 100)
El tamaño de la matriz 4D es: 1200000


In [11]:
#2. Crea una copia de la matriz creada en el ítem anterior(usar método copy)de solo 3 dimensiones (“Cortando una de las dimensiones”)
matriz3d = matriz4d[:,:,:,1].copy() #indexe la matriz original y tome una sola rebanada de esas 4 d1mensiones
print(f"La forma de la matriz 3D es: {matriz3d.shape}")
print(f"El tamaño de la matriz 3D es: {matriz3d.size}")

La forma de la matriz 3D es: (40, 10, 30)
El tamaño de la matriz 3D es: 12000


In [15]:
#3. De la matriz 3D, muestra todos los atributos propios de dicha matriz , dimensión, tamaño, etc..
print(f"La forma de la matriz de 3D es: {matriz3d.shape}")
print(f"Tamaño de la matriz 3D es: {matriz3d.size}")
print(f"Dimensiones matriz 3D es: {matriz3d.ndim}")

La forma de la matriz de 3D es: (40, 10, 30)
Tamaño de la matriz 3D es: 12000
Dimensiones matriz 3D es: 3


In [19]:
#4. Modificar su forma y pasarla a 2D
matriz2d = matriz3d.reshape(40,300)
print(f"La forma de la matriz de 3D es: {matriz2d.shape}")
print(f"Tamaño de la matriz 3D es: {matriz2d.size}")
print(f"Dimensiones matriz 3D es: {matriz2d.ndim}")

La forma de la matriz de 3D es: (40, 300)
Tamaño de la matriz 3D es: 12000
Dimensiones matriz 3D es: 2


In [20]:
#5. Crea una función que reciba la matriz anterior y la pase a un objeto tipo dataframe de Pandas
def matriz_to_dataframe(matriz):
    dataframe = pd.DataFrame(matriz)
    return dataframe

dataframe = matriz_to_dataframe(matriz2d)
print(dataframe)

         0         1         2         3         4         5         6    \
0   0.668515  0.803586  0.830703  0.972339  0.293060  0.625999  0.033666   
1   0.467691  0.723696  0.116838  0.650993  0.917499  0.771889  0.429816   
2   0.811538  0.075550  0.643503  0.649768  0.163642  0.270401  0.330716   
3   0.733558  0.844674  0.898306  0.305343  0.374836  0.516813  0.421200   
4   0.485090  0.758192  0.760991  0.840614  0.431289  0.106567  0.174008   
5   0.438720  0.135011  0.692936  0.509616  0.466402  0.398278  0.449162   
6   0.756028  0.117037  0.423545  0.933509  0.699304  0.363607  0.081337   
7   0.681203  0.774360  0.739225  0.925857  0.616624  0.911075  0.963815   
8   0.589795  0.540481  0.437757  0.848510  0.144922  0.132934  0.531131   
9   0.677435  0.179633  0.368008  0.900334  0.324146  0.924414  0.829085   
10  0.625340  0.595275  0.453391  0.842816  0.036188  0.705115  0.246370   
11  0.868013  0.392265  0.670959  0.357953  0.066217  0.835626  0.221005   
12  0.819653

In [23]:
#6. Crear una función que permita cargar un archivo.mat y .csv 

def cargar(archivo):
    if archivo.endswith('.mat'):
        return sio.loadmat(archivo)
    elif archivo.endswith('.csv'):
        return pd.read_csv(archivo)
    else:
        return("El formato del archivo no es compatible")
    
archivo = r"C:\Users\MARIANA\OneDrive\Escritorio\Informatica II\TallerPreQuiz2\Air_Quality.csv"
data = cargar(archivo)
data

Unique ID  Indicator ID                                         Name  \
0         172653           375                       Nitrogen dioxide (NO2)   
1         172585           375                       Nitrogen dioxide (NO2)   
2         336637           375                       Nitrogen dioxide (NO2)   
3         336622           375                       Nitrogen dioxide (NO2)   
4         172582           375                       Nitrogen dioxide (NO2)   
...          ...           ...                                          ...   
16213     130750           647            Outdoor Air Toxics - Formaldehyde   
16214     130780           647            Outdoor Air Toxics - Formaldehyde   
16215     131020           652  Cardiac and respiratory deaths due to Ozone   
16216     131026           652  Cardiac and respiratory deaths due to Ozone   
16217     325247           643                Annual vehicle miles traveled   

                            Measure Measure Info Geo Type Name  Geo Join ID  \
0                              Mean          ppb         UHF34          203   
1                              Mean          ppb         UHF34          203   
2                              Mean          ppb         UHF34          204   
3                              Mean          ppb         UHF34          103   
4                              Mean          ppb         UHF34          104   
...                             ...          ...           ...          ...   
16213  Annual average concentration        µg/m3         UHF42          211   
16214  Annual average concentration        µg/m3       Borough            5   
16215         Estimated annual rate  per 100,000         UHF42          504   
16216         Estimated annual rate  per 100,000       Borough            5   
16217                 million miles      per km2            CD          107   

                           Geo Place Name          Time Period  Start_Date  \
0      Bedford Stuyvesant - Crown Heights  Annual Average 2011  12/01/2010   
1      Bedford Stuyvesant - Crown Heights  Annual Average 2009  12/01/2008   
2                           East New York  Annual Average 2015  01/01/2015   
3                      Fordham - Bronx Pk  Annual Average 2015  01/01/2015   
4                    Pelham - Throgs Neck  Annual Average 2009  12/01/2008   
...                                   ...                  ...         ...   
16213             Williamsburg - Bushwick                 2005  01/01/2005   
16214                       Staten Island                 2005  01/01/2005   
16215           South Beach - Tottenville            2005-2007  01/01/2005   
16216                       Staten Island            2005-2007  01/01/2005   
16217               Upper West Side (CD7)                 2016  01/01/2016   

       Data Value  Message  
0           25.30      NaN  
1           26.93      NaN  
2           19.09      NaN  
3           19.76      NaN  
4           22.83      NaN  
...           ...      ...  
16213        3.10      NaN  
16214        2.30      NaN  
16215        7.50      NaN  
16216        7.80      NaN  
16217       50.00      NaN  

[16218 rows x 12 columns]

In [29]:
#7. Crear funciones de suma, resta, multiplicación, división,logaritmo ,promedio, desviación estándar NOTA:Estas funciones deben permitir hacer estos procesos a lo largo de un eje (usando Numpy)

# Función de suma a lo largo de un eje
def sum_axis(arr, axis=0):
    return np.sum(arr, axis=axis)

# Función de resta a lo largo de un eje
def subtract_axis(arr1, arr2, axis=0):
    return np.subtract(arr1, arr2)

# Función de multiplicación a lo largo de un eje
def multiply_axis(arr, axis=0):
    return np.prod(arr, axis=axis)

# Función de división a lo largo de un eje
def divide_axis(arr1, arr2, axis=0):
    return np.divide(arr1, arr2)

# Función para calcular el logaritmo a lo largo de un eje
def log_axis(arr, base=10, axis=None):
    return np.log(arr) / np.log(base)

# Función para calcular el promedio a lo largo de un eje
def mean_axis(arr, axis=None):
    return np.mean(arr, axis=axis)

# Función para calcular la desviación estándar a lo largo de un eje
def std_axis(arr, axis=None):
    return np.std(arr, axis=axis) 

In [41]:
#Uso de las funciones anteriores
arr = np.array([[1,2,3],[4,5,6]])
arr1 = np.array([[7,9,3],[1,5,7]])
result_sum = sum_axis(arr, axis=0) #eje 0 son columnas
print(f"la suma a lo largo del eje 0 es: {result_sum}")
result_rest = subtract_axis(arr,arr1, axis=0) #eje 0 son columnas
print(f"la resta a lo largo del eje 0 es: {result_rest}")
result_multip = multiply_axis(arr,axis=0)
print(f"la multiplicación a lo largo del eje 0 es: {result_multip}")
result_div = divide_axis(arr,arr1,axis=0)
print(f"la división a lo largo del eje 0 es: {result_div}")
result_log = log_axis(arr,base =10, axis=0)
print(f"la funcion logaritmo a lo largo del eje 0 es: {result_log}")
result_mean = mean_axis(arr,axis=0)
print(f"el promedio a lo largo del eje 0 es: {result_mean}")
result_std = std_axis(arr,axis=0)
print(f"la desviación estandar a lo largo del eje 0 es: {result_std}")

la suma a lo largo del eje 0 es: [5 7 9]
la resta a lo largo del eje 0 es: [[-6 -7  0]
 [ 3  0 -1]]
la multiplicación a lo largo del eje 0 es: [ 4 10 18]
la división a lo largo del eje 0 es: [[0.14285714 0.22222222 1.        ]
 [4.         1.         0.85714286]]
la funcion logaritmo a lo largo del eje 0 es: [[0.         0.30103    0.47712125]
 [0.60205999 0.69897    0.77815125]]
el promedio a lo largo del eje 0 es: [2.5 3.5 4.5]
la desviación estandar a lo largo del eje 0 es: [1.5 1.5 1.5]
